"""Plain-English trade roadmap.

Turns a validated trade plan into instructions a beginner can follow without
prior trading knowledge, and a live "what do I do right now" instruction that
tracks the current price. Nothing here is generated by a language model — every
sentence is derived from numbers already in the plan, so it cannot hallucinate
a level that the strategy did not produce.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

STAGES = ["WATCHING", "SETUP", "CONFIRMED", "ENTRY_ZONE", "ACTIVE",
          "TP1", "TP2", "CLOSED"]
TERMINAL = {"INVALIDATED", "STOPPED", "EXPIRED", "MISSED", "CLOSED"}

GLOSS = {
    "stop": "If the trade moves against you, this is the planned exit that keeps "
            "the loss controlled.",
    "entry_zone": "The price range where the strategy still considers this trade "
                  "worth taking.",
    "no_chase": "Above this price the move is already extended — the reward no "
                "longer justifies the risk. Let it go.",
    "target": "A price where the plan takes some profit off the table.",
    "r": "R is one unit of risk — the distance from your entry to your stop. "
         "A 2R target aims to make twice what you are risking.",
    "position_size": "The number of shares that keeps your loss at the planned "
                     "amount if the stop is hit.",
    "atr": "Average True Range — a measure of how much this asset typically "
           "moves in one bar.",
    "slippage": "A stop order limits risk but can fill worse than the stop price "
                "in fast markets. Your actual loss can exceed the planned figure.",
}


def money(x: Optional[float], places: int = 2) -> str:
    if x is None:
        return "—"
    return f"${x:,.{places}f}"


def _qty_text(q: float, symbol: str) -> str:
    if symbol.endswith("USD") and q < 100:
        return f"{q:.6f}".rstrip("0").rstrip(".") + " units"
    return f"{q:,.0f} share" + ("s" if q != 1 else "")


def build_roadmap(plan: Dict[str, Any], *, current_price: Optional[float] = None,
                  stage: str = "CONFIRMED",
                  filled: bool = False,
                  targets_hit: Optional[List[str]] = None,
                  strategy_label: str = "",
                  why_lines: Optional[List[str]] = None,
                  checks: Optional[List[Dict[str, Any]]] = None
                  ) -> Dict[str, Any]:
    """Assemble the beginner-facing roadmap for a plan."""
    if not plan.get("actionable"):
        return {
            "headline": plan.get("display_as") or "NO TRADE",
            "stage": "INVALID",
            "now": {"action": "AVOID", "tone": "amber",
                    "title": _no_trade_title(plan),
                    "detail": plan.get("reason", "")
                              + (f"  {plan.get('detail')}" if plan.get("detail") else "")},
            "steps": [], "targets": [], "why": why_lines or [],
            "no_trade_reason": plan.get("reason"),
        }

    d = plan["direction"]
    sym = plan["symbol"]
    entry, stop = plan["entry"], plan["stop"]
    risk = plan["risk"]
    targets = plan["targets"]
    hit = set(targets_hit or [])
    verb = "BUY" if d == "long" else "SELL SHORT"

    # ---- the single most important box: what do I do right now -----------
    now = _what_now(plan, current_price, filled, hit, d, entry, stop, targets)

    # ---- numbered instructions -------------------------------------------
    zone = (plan.get("entry_zone") or {}).get("ideal")
    no_chase = (plan.get("entry_zone") or {}).get("no_chase")
    steps: List[str] = []
    if zone:
        steps.append(f"Wait for price to trade between {money(zone[0])} and "
                     f"{money(zone[1])}. This is the planned entry area.")
    else:
        steps.append(f"Planned entry is {money(entry)}.")
    if no_chase:
        steps.append(f"Do not {verb.split()[0].lower()} above {money(no_chase)} — "
                     f"past that the trade is chasing." if d == "long" else
                     f"Do not short below {money(no_chase)} — past that the trade "
                     f"is chasing.")
    steps.append(f"If you get filled, place your stop at {money(stop)} "
                 f"immediately. That is {money(risk['risk_per_unit'])} per "
                 f"{'share' if not sym.endswith('USD') else 'unit'}.")
    steps.append(f"Size the position at {_qty_text(risk['quantity'], sym)} — that "
                 f"keeps the planned loss at about {money(risk['planned_loss'])}, "
                 f"which is {risk['applied_risk_pct']:.2f}% of your "
                 f"{money(risk['account_equity'], 0)} account.")
    for t in targets:
        steps.append(f"Take {t['allocation_pct']}% off at {money(t['price'])} "
                     f"({t['r']}R — about {money(t['profit_at_target'])} on that "
                     f"portion).")
        if t["name"] == "TP1" and len(targets) > 1:
            steps.append("Once TP1 is filled, move the stop up to your entry price "
                         "so the rest of the trade cannot turn into a loss.")
    if plan.get("invalidation"):
        steps.append(f"Exit immediately if {plan['invalidation']}.")
    if plan.get("expires_at"):
        steps.append(f"If the entry never triggers, the signal expires at "
                     f"{plan['expires_at']} — do not take it late.")

    # ---- the checklist the user can eyeball ------------------------------
    checklist = list(checks or [])
    checklist.append({"ok": True, "label": "Strategy entry conditions confirmed"})
    checklist.append({"ok": plan["rr"]["best"] >= plan["rr"]["min_required"],
                      "label": f"Reward/risk {plan['rr']['best']}R meets the "
                               f"{plan['rr']['min_required']}R minimum"})
    checklist.append({"ok": not risk.get("risk_reduced"),
                      "label": "Full position risk allowed" if not risk.get("risk_reduced")
                      else f"Risk reduced to {risk['applied_risk_pct']:.2f}% "
                           f"({'; '.join(risk['reduction_reasons'][:2])})"})
    pf_after = plan.get("portfolio_after") or {}
    if pf_after:
        checklist.append({
            "ok": pf_after.get("total_open_risk_pct", 0) <= pf_after.get("ceiling_pct", 3),
            "label": f"Portfolio risk after this trade "
                     f"{pf_after.get('total_open_risk_pct', 0):.2f}% of "
                     f"{pf_after.get('ceiling_pct', 3):.1f}% ceiling"})

    return {
        "headline": f"{verb} {sym}",
        "action": verb, "direction": d,
        "strategy": strategy_label,
        "stage": stage,
        "now": now,
        "steps": steps,
        "checklist": checklist,
        "why": why_lines or [],
        "numbers": {
            "entry": entry, "stop": stop,
            "entry_zone": plan.get("entry_zone"),
            "targets": targets,
            "account": risk["account_equity"],
            "risk_pct": risk["applied_risk_pct"],
            "max_loss": risk["planned_loss"],
            "worst_case_with_costs": risk["worst_case_with_costs"],
            "quantity": risk["quantity"],
            "quantity_text": _qty_text(risk["quantity"], sym),
            "position_value": risk["position_notional"],
            "capital_required": risk["capital_required"],
            "estimated_costs": risk["estimated_costs"],
            "rr": plan["rr"],
        },
        "glossary": GLOSS,
        "invalidation": plan.get("invalidation"),
        "expires_at": plan.get("expires_at"),
    }


def _no_trade_title(plan: Dict[str, Any]) -> str:
    return {
        "NO_TRADE_REWARD_TOO_LOW": "Reward does not justify the risk",
        "NO_TRADE_PORTFOLIO_RISK": "Portfolio risk ceiling reached",
        "NO_TRADE_CORRELATION": "Too much correlated exposure already open",
        "TRADE_PLAN_UNAVAILABLE": "Signal detected — trade plan unavailable",
        "SHORTS_DISABLED": "Bearish signal (shorting disabled)",
        "BLOCKED_QC": "Blocked by a safety check",
    }.get(plan.get("status", ""), "No trade")


def _what_now(plan, price, filled, hit, d, entry, stop, targets) -> Dict[str, Any]:
    zone = (plan.get("entry_zone") or {}).get("acceptable")
    no_chase = (plan.get("entry_zone") or {}).get("no_chase")

    if filled:
        remaining = [t for t in targets if t["name"] not in hit]
        if not remaining:
            return {"action": "CLOSED", "tone": "neutral",
                    "title": "All targets reached",
                    "detail": "The planned trade is complete."}
        if hit:
            nxt = remaining[0]
            return {"action": "HOLD", "tone": "positive",
                    "title": f"{', '.join(sorted(hit))} reached — hold the rest",
                    "detail": f"Stop should now be at your entry ({money(entry)}) "
                              f"or better. Next target is {nxt['name']} at "
                              f"{money(nxt['price'])}."}
        if price is not None:
            if (d == "long" and price <= stop) or (d == "short" and price >= stop):
                return {"action": "EXIT", "tone": "negative",
                        "title": "Stop level reached",
                        "detail": f"Price has reached the stop at {money(stop)}. "
                                  f"The plan exits here."}
            t1 = targets[0]
            if (d == "long" and price >= t1["price"]) or (d == "short" and price <= t1["price"]):
                return {"action": f"EXIT {t1['allocation_pct']}%", "tone": "positive",
                        "title": f"Target 1 reached at {money(t1['price'])}",
                        "detail": f"Take {t1['allocation_pct']}% off and move the "
                                  f"stop to breakeven ({money(entry)})."}
        return {"action": "HOLD", "tone": "positive", "title": "Position is active",
                "detail": f"Stop stays at {money(stop)}. First target is "
                          f"{money(targets[0]['price'])}."}

    if price is None:
        return {"action": "WAIT", "tone": "neutral",
                "title": "Waiting for a live price",
                "detail": f"Planned entry {money(entry)}, stop {money(stop)}."}

    if d == "long":
        if no_chase and price > no_chase:
            return {"action": "AVOID", "tone": "amber",
                    "title": f"Too extended — do not chase",
                    "detail": f"Price {money(price)} is above the "
                              f"{money(no_chase)} no-chase level. Wait for the "
                              f"next setup instead."}
        if zone and zone[0] <= price <= zone[1]:
            return {"action": "ENTER", "tone": "positive",
                    "title": "Price is in the entry zone",
                    "detail": f"{money(price)} is inside "
                              f"{money(zone[0])}–{money(zone[1])} and the signal is "
                              f"still valid. Place the stop at {money(stop)} "
                              f"right after you get filled."}
        if price < (zone[0] if zone else entry):
            return {"action": "WAIT", "tone": "neutral",
                    "title": "Below the entry zone",
                    "detail": f"{money(price)} is under the planned area. Either it "
                              f"comes back up into the zone, or the setup is failing "
                              f"— the trade is invalid below {money(stop)}."}
    else:
        if no_chase and price < no_chase:
            return {"action": "AVOID", "tone": "amber",
                    "title": "Too extended — do not chase",
                    "detail": f"Price {money(price)} is below the "
                              f"{money(no_chase)} no-chase level."}
        if zone and zone[0] <= price <= zone[1]:
            return {"action": "ENTER", "tone": "positive",
                    "title": "Price is in the entry zone",
                    "detail": f"{money(price)} is inside the planned area. Stop goes "
                              f"at {money(stop)}."}
    return {"action": "WAIT", "tone": "neutral",
            "title": "Not in the entry zone yet",
            "detail": f"Price is {money(price)}; the plan wants "
                      f"{money(zone[0]) + '–' + money(zone[1]) if zone else money(entry)}. "
                      f"Do not chase."}
