"""initial schema

Revision ID: 42a8fe7314dc
Revises: 
Create Date: 2026-09-01 03:45:49.745029
"""
from alembic import op
import sqlalchemy as sa


revision = '42a8fe7314dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_month'), 'ai_usage', ['month'], unique=False)
    op.create_table('buy_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_uid', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('strategy_version', sa.String(length=24), nullable=False),
    sa.Column('catalyst_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buy_signal_price', sa.Float(), nullable=False),
    sa.Column('price_source', sa.String(length=96), nullable=False),
    sa.Column('provider_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_snapshot', sa.JSON(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=False),
    sa.Column('current_live_price', sa.Float(), nullable=True),
    sa.Column('current_price_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('since_signal_high', sa.Float(), nullable=True),
    sa.Column('since_signal_low', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'strategy_version', 'session_date', 'catalyst_fingerprint', name='uq_signal_idempotency')
    )
    op.create_index(op.f('ix_buy_signals_session_date'), 'buy_signals', ['session_date'], unique=False)
    op.create_index(op.f('ix_buy_signals_signal_uid'), 'buy_signals', ['signal_uid'], unique=True)
    op.create_index(op.f('ix_buy_signals_symbol'), 'buy_signals', ['symbol'], unique=False)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('materiality', sa.Integer(), nullable=False),
    sa.Column('novelty', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('catalyst_type', sa.String(length=64), nullable=False),
    sa.Column('dilution_detected', sa.Boolean(), nullable=False),
    sa.Column('going_concern_detected', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalysts_content_hash'), 'catalysts', ['content_hash'], unique=True)
    op.create_index(op.f('ix_catalysts_symbol'), 'catalysts', ['symbol'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_quotes_symbol'), 'live_quotes', ['symbol'], unique=False)
    op.create_table('market_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('minute_of_day', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'session_date', 'minute_of_day', 'source', name='uq_bar')
    )
    op.create_index('ix_bars_symbol_date', 'market_bars', ['symbol', 'session_date'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_news_hash')
    )
    op.create_index(op.f('ix_news_items_content_hash'), 'news_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_news_items_symbol'), 'news_items', ['symbol'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('data_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_requests_endpoint'), 'provider_requests', ['endpoint'], unique=False)
    op.create_index(op.f('ix_provider_requests_provider'), 'provider_requests', ['provider'], unique=False)
    op.create_table('scanner_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('shortlisted', sa.Integer(), nullable=False),
    sa.Column('enriched', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('primary_doc_url', sa.Text(), nullable=False),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession', 'symbol', name='uq_filing')
    )
    op.create_index(op.f('ix_sec_filings_accession'), 'sec_filings', ['accession'], unique=False)
    op.create_index(op.f('ix_sec_filings_cik'), 'sec_filings', ['cik'], unique=False)
    op.create_index(op.f('ix_sec_filings_form_type'), 'sec_filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_sec_filings_symbol'), 'sec_filings', ['symbol'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('symbol_reference_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_reference_versions_symbol'), 'symbol_reference_versions', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=False),
    sa.Column('security_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_cik'), 'symbols', ['cik'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('block_reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scanner_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_run_id'), 'candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_candidates_session_date'), 'candidates', ['session_date'], unique=False)
    op.create_index(op.f('ix_candidates_symbol'), 'candidates', ['symbol'], unique=False)
    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['buy_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_signal_id'), 'signal_events', ['signal_id'], unique=False)
    op.create_table('signal_price_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_from_signal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['buy_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'label', name='uq_checkpoint')
    )
    op.create_index(op.f('ix_signal_price_checkpoints_signal_id'), 'signal_price_checkpoints', ['signal_id'], unique=False)
    op.create_table('candidate_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('score_detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_feature_snapshots_candidate_id'), 'candidate_feature_snapshots', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_feature_snapshots_candidate_id'), table_name='candidate_feature_snapshots')
    op.drop_table('candidate_feature_snapshots')
    op.drop_index(op.f('ix_signal_price_checkpoints_signal_id'), table_name='signal_price_checkpoints')
    op.drop_table('signal_price_checkpoints')
    op.drop_index(op.f('ix_signal_events_signal_id'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index(op.f('ix_candidates_symbol'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_session_date'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_run_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_cik'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_symbol_reference_versions_symbol'), table_name='symbol_reference_versions')
    op.drop_table('symbol_reference_versions')
    op.drop_table('strategy_versions')
    op.drop_table('settings')
    op.drop_index(op.f('ix_sec_filings_symbol'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_form_type'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_cik'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_accession'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_table('scanner_runs')
    op.drop_index(op.f('ix_provider_requests_provider'), table_name='provider_requests')
    op.drop_index(op.f('ix_provider_requests_endpoint'), table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index(op.f('ix_news_items_symbol'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_content_hash'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_bars_symbol_date', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_index(op.f('ix_live_quotes_symbol'), table_name='live_quotes')
    op.drop_table('live_quotes')
    op.drop_table('health_events')
    op.drop_index(op.f('ix_catalysts_symbol'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_content_hash'), table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_buy_signals_symbol'), table_name='buy_signals')
    op.drop_index(op.f('ix_buy_signals_signal_uid'), table_name='buy_signals')
    op.drop_index(op.f('ix_buy_signals_session_date'), table_name='buy_signals')
    op.drop_table('buy_signals')
    op.drop_index(op.f('ix_ai_usage_month'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
