"""paper accounts and locked outcomes

Revision ID: 529ec9da5b79
Revises: 7248185f8ab8
Create Date: 2026-09-01 15:50:18.058496
"""
from alembic import op
import sqlalchemy as sa


revision = '529ec9da5b79'
down_revision = '7248185f8ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('max_equity', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('trades_closed', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'season', name='uq_account')
    )
    op.create_index(op.f('ix_paper_accounts_model_id'), 'paper_accounts', ['model_id'], unique=False)
    op.create_table('locked_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=48), nullable=False),
    sa.Column('outcome_class', sa.String(length=24), nullable=False),
    sa.Column('call_price', sa.Float(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('reference_quality', sa.String(length=16), nullable=False),
    sa.Column('touch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_of', sa.Integer(), nullable=True),
    sa.Column('revision_reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['buy_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'policy', 'revision_of', name='uq_lock')
    )
    op.create_index(op.f('ix_locked_outcomes_policy'), 'locked_outcomes', ['policy'], unique=False)
    op.create_index(op.f('ix_locked_outcomes_signal_id'), 'locked_outcomes', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locked_outcomes_signal_id'), table_name='locked_outcomes')
    op.drop_index(op.f('ix_locked_outcomes_policy'), table_name='locked_outcomes')
    op.drop_table('locked_outcomes')
    op.drop_index(op.f('ix_paper_accounts_model_id'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
