"""v2 lifecycle paper shadow backtester

Revision ID: 70986ba839fa
Revises: 857f159237c0
Create Date: 2026-09-01 10:44:27.002879
"""
from alembic import op
import sqlalchemy as sa


revision = '70986ba839fa'
down_revision = '857f159237c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bt_cache_cache_key'), 'bt_cache', ['cache_key'], unique=True)
    op.create_table('bt_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bt_jobs_config_hash'), 'bt_jobs', ['config_hash'], unique=False)
    op.create_table('rejected_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('failed_gates', sa.JSON(), nullable=False),
    sa.Column('price_at_reject', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('shadow_high', sa.Float(), nullable=True),
    sa.Column('shadow_low', sa.Float(), nullable=True),
    sa.Column('shadow_last', sa.Float(), nullable=True),
    sa.Column('shadow_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rej_sym_date', 'rejected_candidates', ['symbol', 'session_date'], unique=False)
    op.create_index(op.f('ix_rejected_candidates_session_date'), 'rejected_candidates', ['session_date'], unique=False)
    op.create_index(op.f('ix_rejected_candidates_symbol'), 'rejected_candidates', ['symbol'], unique=False)
    op.create_table('bt_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('universe_n', sa.Integer(), nullable=False),
    sa.Column('candidates_n', sa.Integer(), nullable=False),
    sa.Column('signals_n', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['bt_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'session_date', name='uq_bt_sess')
    )
    op.create_index(op.f('ix_bt_sessions_job_id'), 'bt_sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_bt_sessions_session_date'), 'bt_sessions', ['session_date'], unique=False)
    op.create_table('bt_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('signal_time', sa.String(length=20), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('entry_model', sa.String(length=12), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=48), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('pct', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('fill_ok', sa.Boolean(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['bt_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bt_trades_job_id'), 'bt_trades', ['job_id'], unique=False)
    op.create_index(op.f('ix_bt_trades_session_date'), 'bt_trades', ['session_date'], unique=False)
    op.create_index(op.f('ix_bt_trades_symbol'), 'bt_trades', ['symbol'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_version', sa.String(length=16), nullable=False),
    sa.Column('entry_fill', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('remaining_frac', sa.Float(), nullable=False),
    sa.Column('realized_r', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_reason', sa.String(length=64), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_fill', sa.Float(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['buy_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_signal_id'), 'paper_positions', ['signal_id'], unique=True)
    op.create_index(op.f('ix_paper_positions_symbol'), 'paper_positions', ['symbol'], unique=False)
    op.create_table('shadow_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=40), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['buy_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'policy', name='uq_shadow')
    )
    op.create_index(op.f('ix_shadow_exits_policy'), 'shadow_exits', ['policy'], unique=False)
    op.create_index(op.f('ix_shadow_exits_signal_id'), 'shadow_exits', ['signal_id'], unique=False)
    op.add_column('buy_signals', sa.Column('lifecycle', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('buy_signals', sa.Column('price_tier', sa.String(length=12), nullable=False, server_default=''))
    op.add_column('buy_signals', sa.Column('cohort', sa.String(length=12), nullable=False, server_default=''))
    op.add_column('buy_signals', sa.Column('executable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('buy_signals', sa.Column('data_quality', sa.String(length=12), nullable=False, server_default=''))
    op.add_column('buy_signals', sa.Column('versions', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('buy_signals', sa.Column('sig_bid', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('sig_ask', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('sig_bid_size', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('sig_ask_size', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('sig_spread_pct', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('proposed_entry', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('sim_fill_price', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('no_fill_reason', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('buy_signals', sa.Column('catalyst_published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('sec_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('first_pass_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('first_actionable_quote_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('first_actionable_ask', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('mfe_pct', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('mfe_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('mae_pct', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('mae_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buy_signals', sa.Column('outcome_v2', sa.String(length=12), nullable=False, server_default=''))
    op.create_index(op.f('ix_buy_signals_lifecycle'), 'buy_signals', ['lifecycle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_signals_lifecycle'), table_name='buy_signals')
    op.drop_column('buy_signals', 'outcome_v2')
    op.drop_column('buy_signals', 'mae_at')
    op.drop_column('buy_signals', 'mae_pct')
    op.drop_column('buy_signals', 'mfe_at')
    op.drop_column('buy_signals', 'mfe_pct')
    op.drop_column('buy_signals', 'first_actionable_ask')
    op.drop_column('buy_signals', 'first_actionable_quote_at')
    op.drop_column('buy_signals', 'first_pass_at')
    op.drop_column('buy_signals', 'detected_at')
    op.drop_column('buy_signals', 'sec_accepted_at')
    op.drop_column('buy_signals', 'catalyst_published_at')
    op.drop_column('buy_signals', 'no_fill_reason')
    op.drop_column('buy_signals', 'sim_fill_price')
    op.drop_column('buy_signals', 'proposed_entry')
    op.drop_column('buy_signals', 'sig_spread_pct')
    op.drop_column('buy_signals', 'sig_ask_size')
    op.drop_column('buy_signals', 'sig_bid_size')
    op.drop_column('buy_signals', 'sig_ask')
    op.drop_column('buy_signals', 'sig_bid')
    op.drop_column('buy_signals', 'versions')
    op.drop_column('buy_signals', 'data_quality')
    op.drop_column('buy_signals', 'executable')
    op.drop_column('buy_signals', 'cohort')
    op.drop_column('buy_signals', 'price_tier')
    op.drop_column('buy_signals', 'lifecycle')
    op.drop_index(op.f('ix_shadow_exits_signal_id'), table_name='shadow_exits')
    op.drop_index(op.f('ix_shadow_exits_policy'), table_name='shadow_exits')
    op.drop_table('shadow_exits')
    op.drop_index(op.f('ix_paper_positions_symbol'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_signal_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_bt_trades_symbol'), table_name='bt_trades')
    op.drop_index(op.f('ix_bt_trades_session_date'), table_name='bt_trades')
    op.drop_index(op.f('ix_bt_trades_job_id'), table_name='bt_trades')
    op.drop_table('bt_trades')
    op.drop_index(op.f('ix_bt_sessions_session_date'), table_name='bt_sessions')
    op.drop_index(op.f('ix_bt_sessions_job_id'), table_name='bt_sessions')
    op.drop_table('bt_sessions')
    op.drop_index(op.f('ix_rejected_candidates_symbol'), table_name='rejected_candidates')
    op.drop_index(op.f('ix_rejected_candidates_session_date'), table_name='rejected_candidates')
    op.drop_index('ix_rej_sym_date', table_name='rejected_candidates')
    op.drop_table('rejected_candidates')
    op.drop_index(op.f('ix_bt_jobs_config_hash'), table_name='bt_jobs')
    op.drop_table('bt_jobs')
    op.drop_index(op.f('ix_bt_cache_cache_key'), table_name='bt_cache')
    op.drop_table('bt_cache')
    # ### end Alembic commands ###
