"""strategy profiles

Revision ID: 7248185f8ab8
Revises: 70986ba839fa
Create Date: 2026-09-01 15:26:46.618928
"""
from alembic import op
import sqlalchemy as sa


revision = '7248185f8ab8'
down_revision = '70986ba839fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_signals', sa.Column('profile', sa.String(length=24), nullable=False, server_default='primary'))
    op.create_index(op.f('ix_buy_signals_profile'), 'buy_signals', ['profile'], unique=False)
    op.add_column('paper_positions', sa.Column('profile', sa.String(length=24), nullable=False, server_default='primary'))
    op.create_index(op.f('ix_paper_positions_profile'), 'paper_positions', ['profile'], unique=False)
    op.add_column('rejected_candidates', sa.Column('profile', sa.String(length=24), nullable=False, server_default='primary'))
    op.create_index(op.f('ix_rejected_candidates_profile'), 'rejected_candidates', ['profile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejected_candidates_profile'), table_name='rejected_candidates')
    op.drop_column('rejected_candidates', 'profile')
    op.drop_index(op.f('ix_paper_positions_profile'), table_name='paper_positions')
    op.drop_column('paper_positions', 'profile')
    op.drop_index(op.f('ix_buy_signals_profile'), table_name='buy_signals')
    op.drop_column('buy_signals', 'profile')
    # ### end Alembic commands ###
