"""quant lab tables

Revision ID: 74c788a3cf5a
Revises: a1343e438d9f
Create Date: 2026-09-03 22:11:19.738234
"""
from alembic import op
import sqlalchemy as sa


revision = '74c788a3cf5a'
down_revision = 'a1343e438d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=48), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('by_regime', sa.JSON(), nullable=False),
    sa.Column('by_session', sa.JSON(), nullable=False),
    sa.Column('by_symbol', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('monthly', sa.JSON(), nullable=False),
    sa.Column('costs', sa.JSON(), nullable=False),
    sa.Column('data_coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_runs_market'), 'lab_runs', ['market'], unique=False)
    op.create_index(op.f('ix_lab_runs_strategy_id'), 'lab_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_lab_runs_timeframe'), 'lab_runs', ['timeframe'], unique=False)
    op.create_index('ix_labrun_lookup', 'lab_runs', ['strategy_id', 'market', 'timeframe', 'kind', 'split'], unique=False)
    op.create_table('lab_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('markets', sa.JSON(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('hold', sa.String(length=24), nullable=False),
    sa.Column('stop_method', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('stage_reason', sa.Text(), nullable=False),
    sa.Column('optimization_count', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('best_market', sa.String(length=16), nullable=False),
    sa.Column('best_timeframe', sa.String(length=8), nullable=False),
    sa.Column('best_regime', sa.String(length=24), nullable=False),
    sa.Column('worst_regime', sa.String(length=24), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_strategies_family'), 'lab_strategies', ['family'], unique=False)
    op.create_index(op.f('ix_lab_strategies_stage'), 'lab_strategies', ['stage'], unique=False)
    op.create_index(op.f('ix_lab_strategies_strategy_id'), 'lab_strategies', ['strategy_id'], unique=True)
    op.create_table('lab_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=48), nullable=False),
    sa.Column('cohort', sa.String(length=16), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('session_bucket', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_trades_cohort'), 'lab_trades', ['cohort'], unique=False)
    op.create_index(op.f('ix_lab_trades_market'), 'lab_trades', ['market'], unique=False)
    op.create_index(op.f('ix_lab_trades_regime'), 'lab_trades', ['regime'], unique=False)
    op.create_index(op.f('ix_lab_trades_result'), 'lab_trades', ['result'], unique=False)
    op.create_index(op.f('ix_lab_trades_session_bucket'), 'lab_trades', ['session_bucket'], unique=False)
    op.create_index(op.f('ix_lab_trades_signal_time'), 'lab_trades', ['signal_time'], unique=False)
    op.create_index(op.f('ix_lab_trades_strategy_id'), 'lab_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_lab_trades_symbol'), 'lab_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_lab_trades_timeframe'), 'lab_trades', ['timeframe'], unique=False)
    op.create_index('ix_labtrade_lookup', 'lab_trades', ['strategy_id', 'cohort', 'market', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labtrade_lookup', table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_timeframe'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_symbol'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_strategy_id'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_signal_time'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_session_bucket'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_result'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_regime'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_market'), table_name='lab_trades')
    op.drop_index(op.f('ix_lab_trades_cohort'), table_name='lab_trades')
    op.drop_table('lab_trades')
    op.drop_index(op.f('ix_lab_strategies_strategy_id'), table_name='lab_strategies')
    op.drop_index(op.f('ix_lab_strategies_stage'), table_name='lab_strategies')
    op.drop_index(op.f('ix_lab_strategies_family'), table_name='lab_strategies')
    op.drop_table('lab_strategies')
    op.drop_index('ix_labrun_lookup', table_name='lab_runs')
    op.drop_index(op.f('ix_lab_runs_timeframe'), table_name='lab_runs')
    op.drop_index(op.f('ix_lab_runs_strategy_id'), table_name='lab_runs')
    op.drop_index(op.f('ix_lab_runs_market'), table_name='lab_runs')
    op.drop_table('lab_runs')
    # ### end Alembic commands ###
