"""post window extremes

Revision ID: 857f159237c0
Revises: f4abefc8ebd5
Create Date: 2026-09-01 05:28:45.412739
"""
from alembic import op
import sqlalchemy as sa


revision = '857f159237c0'
down_revision = 'f4abefc8ebd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_signals', sa.Column('post_window_high', sa.Float(), nullable=True))
    op.add_column('buy_signals', sa.Column('post_window_low', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_signals', 'post_window_low')
    op.drop_column('buy_signals', 'post_window_high')
    # ### end Alembic commands ###
