"""signal_type on buy_signals

Revision ID: f4abefc8ebd5
Revises: 42a8fe7314dc
Create Date: 2026-09-01 05:15:56.060411
"""
from alembic import op
import sqlalchemy as sa


revision = 'f4abefc8ebd5'
down_revision = '42a8fe7314dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_signals', sa.Column('signal_type', sa.String(length=8),
                                           nullable=False, server_default='buy'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_signals', 'signal_type')
    # ### end Alembic commands ###
