/** Plain-English explanations shown in popovers across the app. */
/** Full glossary — every acronym and term used anywhere in the app. */
export const GLOSSARY: Record<string, string> = {
  'RVOL': 'Relative Volume — today\'s volume vs what is typical for this stock by this time of day. 3x+ = unusual attention. EST = estimated until enough history exists.',
  'VWAP': 'Volume-Weighted Average Price — the session\'s average price weighted by shares traded. Above VWAP = buyers in control.',
  'MFE': 'Maximum Favorable Excursion — the best unrealized profit a trade reached after entry. A diagnostic, not a result you captured.',
  'MAE': 'Maximum Adverse Excursion — the worst unrealized loss a trade suffered after entry.',
  'PF': 'Profit Factor — gross profits ÷ gross losses, after costs. Above 1.0 = profitable. 2.0 = made $2 for every $1 lost.',
  'DD / Max DD': 'Maximum Drawdown — the largest peak-to-trough equity decline. Measures the worst losing stretch.',
  'R / R-multiple': 'Risk multiple — profit measured in units of initial risk. Entry $10, stop $9 → risk $1; selling at $12 = +2R.',
  'T1 / T2': 'Target 1 / Target 2 — the sell plan. At T1 the paper position takes 50% off and moves the stop to breakeven; at T2 the rest exits.',
  'BE': 'Breakeven — moving the stop to the entry price so the remaining position cannot turn into a loss.',
  'WR': 'Win Rate — winning trades ÷ decided trades.',
  'LB (Wilson LB)': 'Wilson Lower Bound — a conservative floor on the true win rate given sample size. 3 wins in 3 trades has a LOW bound; 300/500 has a tight one. Prevents tiny samples from looking perfect.',
  'EXP (badge)': 'Experimental model — a Claude-designed hypothesis, clearly unproven until forward evidence exists.',
  'exp% / Expectancy': 'Average profit per trade after estimated costs, in percent. The single most important number.',
  'PM': 'Premarket — 4:00–9:30 AM ET extended-hours trading.',
  'RTH': 'Regular Trading Hours — 9:30 AM–4:00 PM ET.',
  'EOD': 'End Of Day — daily bar data.',
  'OHLCV': 'Open, High, Low, Close, Volume — the five fields of a price bar.',
  'ATR': 'Average True Range — the average size of a bar\'s full movement; a volatility measure used for stops.',
  'SMA': 'Simple Moving Average — the average close over N bars.',
  'RSI': 'Relative Strength Index (0–100) — momentum oscillator; >70 stretched up, <30 stretched down.',
  'MACD': 'Moving Average Convergence/Divergence — trend-momentum indicator from two EMAs.',
  'Gap %': 'Percent move vs the previous session\'s close.',
  'Float': 'Shares actually available to trade publicly (excludes insider/locked shares). Low float = explosive moves.',
  'Float rotation': 'Premarket volume ÷ float — how many times the tradable share supply has changed hands. >100% = the whole float traded.',
  'Spread': 'Gap between best bid and ask as % of price. Wide spreads make round-trips expensive.',
  'Slippage': 'The price concession assumed on fills — buys assume paying slightly above the ask, sells slightly below the bid.',
  'Bid / Ask': 'Best price buyers will pay (bid) / sellers will accept (ask). You buy at the ask, sell at the bid.',
  'Catalyst grade A/B/C/R': 'A = hard event (FDA, merger, major contract). B = meaningful (order, partnership). C = weak (vague PR, conference). R = reject-quality (promo, dilution).',
  'Materiality': 'How much the catalyst matters for a company this size — transformative / major / moderate / minor / immaterial.',
  'Dilution': 'New shares entering the market (offerings, ATMs, converts, warrants) — supply that caps rallies.',
  'ATM (dilution)': 'At-The-Market program — the company can sell new shares directly into rallies.',
  'Lifecycle states': 'DISCOVERED → EARLY_WATCH (pre-7:00, not tradable) → QUALIFIED_WATCH → ACTIONABLE_BUY → CLOSED. Or REJECTED / INVALIDATED / EXPIRED / DATA_ERROR.',
  'EARLY WATCH': 'Passed every gate except the clock — brokers don\'t allow premarket orders before 7:00 ET, so it cannot be a BUY yet.',
  'AMBIGUOUS': 'Stop and target both hit inside one bar with unknown order — never counted as a win.',
  'NO_FILL': 'The book couldn\'t realistically fill the order (too little size or too wide a spread) — no hypothetical profit is recorded.',
  'Cohort': 'Which evidence bucket a statistic comes from: development / validation / walk-forward / holdout / live paper. Never mixed.',
  'Walk-forward (WF)': 'Repeated train-on-past, test-on-next-unseen-period evaluation. The honest version of a backtest.',
  'Holdout': 'A final untouched time period evaluated exactly once after the strategy is locked.',
  'OOS': 'Out-Of-Sample — performance on data the strategy was never tuned on. The only kind that predicts anything.',
  'PBO': 'Probability of Backtest Overfitting — estimate of how likely the "best" config is only best by luck.',
  'UNCALIBRATED': 'Not enough trades yet for the score/probability to mean anything (needs ~50+).',
  'Paper trading': 'Simulated trading with realistic fills and costs but no real money and no real orders.',
  'Ledger': 'The append-only account record — cash, positions, and P&L derive from it, never from screen memory.',
  'Regime': 'Market condition classification (trend / range / event / high-risk / uncertain) that gates which models may trade.',
  'LIVE / STALE / ESTIMATED': 'Data freshness labels. STALE = old print (blocked from BUYs). ESTIMATED = derived value, clearly lower confidence.',
  'WIN_10_TOUCH': 'Scalper noon rule: price touched +10% from the call before noon — locked as a call-accuracy WIN even if it faded after.',
  'MFE decay': 'Average unrealized profit at each minute after entry — shows whether profits peak early or build into the open.',
  'Sharpe / Sortino': 'Risk-adjusted return measures — return per unit of volatility (Sortino counts only downside).',
};

export const TERMS: Record<string, string> = {
  score: 'Deterministic 0–100 rating: momentum/volume (30) + catalyst (25) + SEC filings (15) + liquidity (10) + price confirmation (10) + company quality (10), minus risk penalties. BUY needs ≥75.',
  price: 'Latest premarket trade print. ~ means indicative bid/ask midpoint because no fresh trade has printed yet.',
  gap: 'Percent move vs yesterday’s regular-session close. The core “gapper” metric.',
  rvol: 'Relative volume — today’s premarket volume vs what’s typical for this stock by this time of morning. 3x+ means unusual attention. EST = estimated from average daily volume until per-symbol history builds.',
  pm_vol: 'Shares traded so far this premarket session (observed from the extended-hours tape).',
  pm_dvol: 'Dollar value traded so far premarket (price × volume). Filters out moves nobody can actually trade.',
  float: 'Shares actually available for public trading (excludes insiders/locked shares). Small float + big demand = explosive moves.',
  float_rot: 'Float rotation — what fraction of the entire float has already changed hands premarket. 50%+ means the stock is heavily “in play”.',
  mkt_cap: 'Total company value (price × all shares outstanding). Micro caps (<$300M) move hardest in percent terms.',
  spread: 'Gap between best bid and ask as % of price. Wide spreads make entries/exits expensive; >5% blocks BUY.',
  vwap: 'Volume-weighted average price of today’s premarket. Price holding above VWAP = buyers in control.',
  shares_out: 'All shares that exist for the company, including insider/locked shares.',
  avg_vol: 'Average daily volume over recent months — the baseline for RVOL.',
  catalyst: 'The verified reason for the move: news and/or SEC filings, AI-classified for direction, materiality (0–100), novelty, and confidence.',
  filings: 'SEC filings from the last 7 days. Click any chip to read the original on EDGAR.',
  status: 'watching = being measured · gated = fails a universe/volume rule (reason shown) · blocked = risk hard-stop · EARLY = fully qualified, waiting for the 7:00 broker window · qualified = BUY fired.',
  buy_price: 'Immutable price at the moment the signal fired. Never changes, ever.',
  current: 'Latest validated live price — updates separately from the BUY price.',
  change: 'Percent move from signal price to current price.',
  day_hilo: 'Highest and lowest prices across today’s session.',
  since_hilo: 'Highest and lowest prices observed since the signal fired.',
  max_gain: 'Best-case: highest % above the signal price reached since it fired.',
  max_dd: 'Worst-case: lowest % below the signal price reached since it fired.',
  outcome: 'Judged ONLY on the first minutes after the pick becomes tradable (7:00 window or signal time): up ≥ threshold inside it = WIN locked forever; down ≥ threshold without the pop = LOSS; neither = NEUTRAL. Never re-judged hours later.',
  signal_type: 'BUY = every gate passed. WATCH = notable pick (score ≥ threshold, real volume, fresh price) recorded and tracked identically, but not fully qualified.',
  checkpoints: 'Snapshots taken 5/15/30/60 minutes after the signal and at the close.',
};

/** Plain-English definitions for `Term` popovers in Simple mode (spec §4.6 / §8 A8).
 *  Keyed by glossary key; `Term` falls back to TERMS, then GLOSSARY. */
export const PLAIN: Record<string, string> = {
  early_pop: 'Did the stock go up in the first few minutes after it became tradable? Judged once, in that window, and never re-judged later. "Flat" means it did neither.',
  noon_check: 'At 12:00 ET we look once: is the stock above the price it was picked at? A green noon counts as right, a red noon as wrong.',
  conservative_floor: 'A cautious version of the win rate that allows for small samples. With few trades the floor is far below the raw rate; with hundreds it is close. Good for comparing strategies with different trade counts.',
  r_multiple: 'Profit measured in units of what was risked. Risking $1 per share and making $2 is +2R; losing the full risk is −1R.',
  paper: 'Simulated money. Fills use real prices with a cost estimate, but no real order is ever placed.',
  tracked: 'Signal outcomes measured from the pick price — not an account, not money. Shows whether picks tend to work, not what they earned.',
  backtest: 'A replay of the rules over past data. Useful for finding problems, never proof of future results.',
  drawdown_account: 'The worst dip in the paper account\'s value from its highest point, as a percentage of the $10,000 it started with.',
  drawdown_sum: 'The worst run of losing trades, adding each trade\'s percentage result. Not an account figure.',
  gap: 'How far today\'s price is from yesterday\'s close, in percent. A big gap means something happened overnight.',
  score_plain: 'A 0–100 rating of how closely a stock matches the strategy\'s rules right now. Higher is a better match — it is not a probability of profit.',
  pipeline: 'Where today\'s stocks are in the process: found → early watch → watching → buy pick, or blocked, dropped, expired, closed.',
  regime: 'The system\'s read of the market\'s mood today — trending, range-bound, event-driven, high risk or uncertain. Some strategies sit out in some regimes.',
  ceiling_floor: 'A ceiling is a price level the stock has struggled to rise above; a floor is one it has struggled to fall below. Drawn automatically from past turns.',
  whats_missing: 'The first check this stock is failing, with the value it has and the value it needs. Fix that and it moves closer to a Buy pick.',
  ambiguous: 'The stop and the target were both hit inside one bar, so we cannot know which came first. Counted as unclear, never as a win.',
  legacy_bucket: 'Picks recorded before lifecycle states existed. Kept for the totals; they cannot be classified further.',
  pop_rate_incl_flat: 'Share of picks that popped, counting flat outcomes as misses. Lower than the decided-only rate because flats sit in the denominator.',
  signals_today: 'Buy picks this strategy has issued during today\'s session.',
  // Accuracy board (spec §3.6) column words
  expectancy_r: 'Average result per trade in units of what was risked (R). Ranks above win rate: a strategy can be right often and still lose money.',
  profit_factor: 'Everything the winning trades made divided by everything the losing trades lost. Above 1 means the wins outweigh the losses.',
  backtest_dev: 'Measured on the data the rules were tuned on. Flattering by construction — the least informative column.',
  backtest_holdout: 'Measured once on data the tuning never saw. When it disagrees with the dev column, believe this one.',
  engine_version: 'The version of the scanner logic that produced these picks. Materially different rules get a new version and their own results pool.',
};
