/** Plain-English explanations shown as tooltips across the app. */
export const TERMS: Record<string, string> = {
  score: 'Deterministic 0–100 rating: momentum/volume (30) + catalyst (25) + SEC filings (15) + liquidity (10) + price confirmation (10) + company quality (10), minus risk penalties. BUY needs ≥75.',
  price: 'Latest premarket trade print. ~ means indicative bid/ask midpoint because no fresh trade has printed yet.',
  gap: 'Percent move vs yesterday’s regular-session close. The core “gapper” metric.',
  rvol: 'Relative volume — today’s premarket volume vs what’s typical for this stock by this time of morning. 3x+ means unusual attention. EST = estimated from average daily volume until per-symbol history builds.',
  pm_vol: 'Shares traded so far this premarket session (observed from the extended-hours tape).',
  pm_dvol: 'Dollar value traded so far premarket (price × volume). Filters out moves nobody can actually trade.',
  float: 'Shares actually available for public trading (excludes insiders/locked shares). Small float + big demand = explosive moves.',
  float_rot: 'Float rotation — what fraction of the entire float has already changed hands premarket. 50%+ means the stock is heavily “in play”.',
  mkt_cap: 'Total company value (price × all shares outstanding). Micro caps (<$300M) move hardest in percent terms.',
  spread: 'Gap between best bid and ask as % of price. Wide spreads make entries/exits expensive; >5% blocks BUY.',
  vwap: 'Volume-weighted average price of today’s premarket. Price holding above VWAP = buyers in control.',
  shares_out: 'All shares that exist for the company, including insider/locked shares.',
  avg_vol: 'Average daily volume over recent months — the baseline for RVOL.',
  catalyst: 'The verified reason for the move: news and/or SEC filings, AI-classified for direction, materiality (0–100), novelty, and confidence.',
  filings: 'SEC filings from the last 7 days. Click any chip to read the original on EDGAR.',
  status: 'watching = being measured · gated = fails a universe/volume rule (reason shown) · blocked = risk hard-stop · EARLY = fully qualified, waiting for the 7:00 broker window · qualified = BUY fired.',
  buy_price: 'Immutable price at the moment the signal fired. Never changes, ever.',
  current: 'Latest validated live price — updates separately from the BUY price.',
  change: 'Percent move from signal price to current price.',
  day_hilo: 'Highest and lowest prices across today’s session.',
  since_hilo: 'Highest and lowest prices observed since the signal fired.',
  max_gain: 'Best-case: highest % above the signal price reached since it fired.',
  max_dd: 'Worst-case: lowest % below the signal price reached since it fired.',
  signal_type: 'BUY = every gate passed. WATCH = notable pick (score ≥ threshold, real volume, fresh price) recorded and tracked identically, but not fully qualified.',
  checkpoints: 'Snapshots taken 5/15/30/60 minutes after the signal and at the close.',
};
